block:
  break:
    stone:
      default:
        chance: 75.0
        rewards:
          economy-minimum: 0
          economy-maximum: 4
          commands:
          - "say {player} broke a stone! (default)"
      vip:
        chance: 75.0
        rewards:
          economy-minimum: 0
          economy-maximum: 8
          commands:
          - "say {player} broke a stone! (VIP)"
