# Block related settings and rewardable activities.
block:
  # Block break rewardable activities section.
  # Block break rewardable activities trigger on block break.
  break:
    # Block type.
    stone:
      # Groups with the rewards.
      # There has to be a 'default' group at least.
      # There can also be more groups but the "better" ones should be below the others.
      # For example:
      # default ("the worst" group -> first)
      # vip ("better than the default" group -> below the 'default' group)
      # mvp ("better than the vip" group -> below the 'vip' group)
      # Permission to be able to receive group rewards: 'rewardableactivities.group.<group>'
      # (default group does not require this permission)
      # Default reward group.
      default:
        # Chance to obtain this reward.
        chance: 75.0
        # Economy settings (require Vault and economy plugin to be used).
        # Economy settings can be ommited if ^ conditions are not met.
        # Minimum economy that the player will receive.
        minimum-economy: 0.0
        # Maximum economy that the player will receive.
        maximum-economy: 4.0
        # Commands that will be executed.
        # Available placeholders:
        # {player} -> player name
        commands:
        - "say {player} broke a stone! ({group})"
      # Additional reward group.
      vip:
        chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 8.0
        commands:
        - "say {player} broke a stone! ({group})"
      # Additional reward group.
      mvip:
        chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 16.0
        commands:
        - "say {player} broke a stone! ({group})"
    grass_block:
      default:
        chance: 100.0
        commands:
        - "say {player} broke a grass block! ({group})"
  # Block place rewardable activities section.
  # Block place rewardable activities have the same exact settings as the block break ones.
  # Block place rewardable activities trigger on block place.
  place:
    diamond_block:
      default:
        chance: 100.0
        commands:
        - "say {player} placed a diamond block! ({group})"

# Entity related settings and rewardable activities.
entity:
  # Entity kill rewardable activities section.
  # Entity kill rewardable activities trigger on entity kill.
  kill:
    # Entity type.
    zombie:
      # Groups with the rewards.
      # There has to be a 'default' group at least.
      # There can also be more groups but the "better" ones should be below the others.
      # For example:
      # default ("the worst" group -> first)
      # vip ("better than the default" group -> below the 'default' group)
      # mvp ("better than the vip" group -> below the 'vip' group)
      # Permission to be able to receive group rewards: 'rewardableactivities.group.<group>'
      # (default group does not require this permission)
      # Default reward group.
      default:
        # Chance to obtain this reward.
        chance: 75.0
        # Economy settings (require Vault and economy plugin to be used).
        # Economy settings can be ommited if ^ conditions are not met.
        # Minimum economy that the player will receive.
        minimum-economy: 0.0
        # Maximum economy that the player will receive.
        maximum-economy: 4.0
        # Commands that will be executed.
        # Available placeholders:
        # {player} -> player name
        commands:
        - "say {player} killed a zombie! ({group})"
      # Additional reward group.
      vip:
        chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 8.0
        commands:
        - "say {player} killed a zombie! ({group})"
      # Additional reward group.
      mvip:
        chance: 75.0
        minimum-economy: 0.0
        maximum-economy: 16.0
        commands:
        - "say {player} killed a zombie! ({group})"
    pig:
      default:
        chance: 100.0
        commands:
        - "say {player} killed a pig! ({group})"
  # Entity breed rewardable activities section.
  # Entity breed rewardable activities have the same exact settings as the entity kill ones.
  # Entity breed rewardable activities trigger on entity kill.
  breed:
    pig:
      default:
        chance: 100.0
        commands:
        - "say {player} bred a pig! ({group})"
