block:
  break:
    stone:
      default:
        chance: 75.0
        minimum-economy: 0
        maximum-economy: 4
        commands:
        - "say {player} broke a stone! (default)"
      vip:
        chance: 75.0
        minimum-economy: 0
        maximum-economy: 8
        commands:
        - "say {player} broke a stone! (VIP)"
    grass_block:
      default:
        chance: 100.0
        commands:
        - "say {player} broke a grass block! (default)"
